$(document).ready(function(){
	$("#i1").click(function(){
		$(this).hide();
		$("#i2").show();
		$(".rMenuI").slideDown(300);
	});
	$("#i2").click(function(){
		$(this).hide();
		$("#i1").show();
		$(".rMenuI").slideUp(300);
	});
});